-- Auto-generated by matugen
-- Material You colors for Neovim

local M = {}

-- Helper function to increase saturation for more vivid colors
local function saturate(hex, amount)
  amount = amount or 0.3  -- 0.0 to 1.0 scale

  -- Convert hex to RGB
  local r = tonumber(hex:sub(2, 3), 16) / 255
  local g = tonumber(hex:sub(4, 5), 16) / 255
  local b = tonumber(hex:sub(6, 7), 16) / 255

  -- Convert RGB to HSL
  local max = math.max(r, g, b)
  local min = math.min(r, g, b)
  local h, s, l = 0, 0, (max + min) / 2

  if max ~= min then
    local d = max - min
    s = l > 0.5 and d / (2 - max - min) or d / (max + min)

    if max == r then
      h = (g - b) / d + (g < b and 6 or 0)
    elseif max == g then
      h = (b - r) / d + 2
    else
      h = (r - g) / d + 4
    end
    h = h / 6
  end

  -- Increase saturation
  s = math.min(1, s + amount)

  -- Convert HSL back to RGB
  local function hue2rgb(p, q, t)
    if t < 0 then t = t + 1 end
    if t > 1 then t = t - 1 end
    if t < 1/6 then return p + (q - p) * 6 * t end
    if t < 1/2 then return q end
    if t < 2/3 then return p + (q - p) * (2/3 - t) * 6 end
    return p
  end

  if s == 0 then
    r, g, b = l, l, l
  else
    local q = l < 0.5 and l * (1 + s) or l + s - l * s
    local p = 2 * l - q
    r = hue2rgb(p, q, h + 1/3)
    g = hue2rgb(p, q, h)
    b = hue2rgb(p, q, h - 1/3)
  end

  -- Convert back to hex
  return string.format("#%02x%02x%02x",
    math.floor(r * 255 + 0.5),
    math.floor(g * 255 + 0.5),
    math.floor(b * 255 + 0.5)
  )
end

-- Core colors
M.colors = {
  background = "#131315",
  foreground = "#e5e1e3",

  -- Primary colors
  primary = "#c6c5d6",
  on_primary = "#2e2f3d",
  primary_container = "#454654",
  on_primary_container = "#e2e1f3",

  -- Secondary colors
  secondary = "#c7c5d0",
  on_secondary = "#2f3038",
  secondary_container = "#46464f",
  on_secondary_container = "#e3e1ec",

  -- Tertiary colors
  tertiary = "#c4c5dd",
  on_tertiary = "#2d2f42",
  tertiary_container = "#444559",
  on_tertiary_container = "#e0e0f9",

  -- Surface colors
  surface = "#131315",
  on_surface = "#e5e1e3",
  surface_variant = "#474648",
  on_surface_variant = "#c9c6c7",
  surface_container = "#201f21",
  surface_container_high = "#2a2a2b",
  surface_container_highest = "#353436",
  surface_container_low = "#1c1b1d",
  surface_bright = "#3a393a",
  surface_dim = "#131315",

  -- Error colors
  error = "#ffb4ab",
  on_error = "#690005",
  error_container = "#93000a",
  on_error_container = "#ffdad6",

  -- Outline
  outline = "#929092",
  outline_variant = "#474648",

  -- Inverse colors
  inverse_surface = "#e5e1e3",
  inverse_on_surface = "#313032",
  inverse_primary = "#5d5d6c",

  -- Other
  shadow = "#000000",
  scrim = "#000000",
}

-- Create saturated versions for syntax highlighting (more vivid colors)
M.bright_colors = {
  primary = saturate(M.colors.primary, 0.4),
  secondary = saturate(M.colors.secondary, 0.4),
  tertiary = saturate(M.colors.tertiary, 0.4),
  on_surface = saturate(M.colors.on_surface, 0.2),
  on_surface_variant = saturate(M.colors.on_surface_variant, 0.3),
  outline = saturate(M.colors.outline, 0.35),
}

function M.setup()
  local c = M.colors
  local b = M.bright_colors

  -- Editor highlights
  vim.api.nvim_set_hl(0, "Normal", { fg = c.on_background, bg = "NONE" })
  vim.api.nvim_set_hl(0, "NormalFloat", { fg = c.on_surface, bg = c.surface_container })
  vim.api.nvim_set_hl(0, "FloatBorder", { fg = c.outline, bg = c.surface_container })
  vim.api.nvim_set_hl(0, "FloatTitle", { fg = c.primary, bg = c.surface_container })

  -- Cursor
  vim.api.nvim_set_hl(0, "Cursor", { fg = c.background, bg = c.on_background })
  vim.api.nvim_set_hl(0, "CursorLine", { bg = c.surface_container_low })
  vim.api.nvim_set_hl(0, "CursorLineNr", { fg = c.primary, bold = true })
  vim.api.nvim_set_hl(0, "LineNr", { fg = c.outline_variant })

  -- Selection
  vim.api.nvim_set_hl(0, "Visual", { bg = c.primary_container })
  vim.api.nvim_set_hl(0, "VisualNOS", { bg = c.primary_container })

  -- Search
  vim.api.nvim_set_hl(0, "Search", { fg = c.on_tertiary_container, bg = c.tertiary_container })
  vim.api.nvim_set_hl(0, "IncSearch", { fg = c.on_primary, bg = c.primary })
  vim.api.nvim_set_hl(0, "CurSearch", { fg = c.on_primary, bg = c.primary })

  -- UI Elements
  vim.api.nvim_set_hl(0, "StatusLine", { fg = c.on_surface, bg = c.surface_container })
  vim.api.nvim_set_hl(0, "StatusLineNC", { fg = c.on_surface_variant, bg = c.surface_container_low })
  vim.api.nvim_set_hl(0, "VertSplit", { fg = c.outline_variant })
  vim.api.nvim_set_hl(0, "WinSeparator", { fg = c.outline_variant })
  vim.api.nvim_set_hl(0, "SignColumn", { bg = "NONE" })
  vim.api.nvim_set_hl(0, "Pmenu", { fg = c.on_surface, bg = c.surface_container })
  vim.api.nvim_set_hl(0, "PmenuSel", { fg = c.on_primary_container, bg = c.primary_container })
  vim.api.nvim_set_hl(0, "PmenuSbar", { bg = c.surface_container_high })
  vim.api.nvim_set_hl(0, "PmenuThumb", { bg = c.outline })

  -- Syntax highlighting (using 3 distinct saturated colors)
  -- Comments - muted
  vim.api.nvim_set_hl(0, "Comment", { fg = b.outline, italic = true })

  -- Strings and Constants - TERTIARY (color 1)
  vim.api.nvim_set_hl(0, "Constant", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "String", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "Character", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "Number", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "Boolean", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "Float", { fg = b.tertiary })

  -- Variables and Identifiers - plain text
  vim.api.nvim_set_hl(0, "Identifier", { fg = b.on_surface })

  -- Functions - PRIMARY (color 2)
  vim.api.nvim_set_hl(0, "Function", { fg = b.primary })

  -- Keywords and Control Flow - SECONDARY (color 3)
  vim.api.nvim_set_hl(0, "Statement", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "Conditional", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "Repeat", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "Label", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "Operator", { fg = b.on_surface_variant })
  vim.api.nvim_set_hl(0, "Keyword", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "Exception", { fg = c.error })

  -- Preprocessor - SECONDARY (color 3)
  vim.api.nvim_set_hl(0, "PreProc", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "Include", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "Define", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "Macro", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "PreCondit", { fg = b.secondary })

  -- Types - PRIMARY (color 2)
  vim.api.nvim_set_hl(0, "Type", { fg = b.primary })
  vim.api.nvim_set_hl(0, "StorageClass", { fg = b.primary })
  vim.api.nvim_set_hl(0, "Structure", { fg = b.primary })
  vim.api.nvim_set_hl(0, "Typedef", { fg = b.primary })

  -- Special - TERTIARY (color 1)
  vim.api.nvim_set_hl(0, "Special", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "SpecialChar", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "Tag", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "Delimiter", { fg = b.on_surface_variant })
  vim.api.nvim_set_hl(0, "SpecialComment", { fg = b.outline, italic = true })
  vim.api.nvim_set_hl(0, "Debug", { fg = c.error })

  vim.api.nvim_set_hl(0, "Underlined", { underline = true })
  vim.api.nvim_set_hl(0, "Error", { fg = c.error })
  vim.api.nvim_set_hl(0, "Todo", { fg = c.on_tertiary_container, bg = c.tertiary_container, bold = true })

  -- Diff
  vim.api.nvim_set_hl(0, "DiffAdd", { fg = c.tertiary, bg = c.surface_container_low })
  vim.api.nvim_set_hl(0, "DiffChange", { fg = c.secondary, bg = c.surface_container_low })
  vim.api.nvim_set_hl(0, "DiffDelete", { fg = c.error, bg = c.surface_container_low })
  vim.api.nvim_set_hl(0, "DiffText", { fg = c.primary, bg = c.surface_container_high })

  -- Git signs
  vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "GitSignsChange", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = c.error })

  -- Diagnostics
  vim.api.nvim_set_hl(0, "DiagnosticError", { fg = c.error })
  vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = c.primary })
  vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.error })
  vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = c.secondary })
  vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = c.primary })
  vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = c.tertiary })

  -- LSP
  vim.api.nvim_set_hl(0, "LspReferenceText", { bg = c.surface_container_high })
  vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = c.surface_container_high })
  vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = c.surface_container_high })

  -- Treesitter (using 3 distinct saturated colors)
  -- Variables - plain text
  vim.api.nvim_set_hl(0, "@variable", { fg = b.on_surface })
  vim.api.nvim_set_hl(0, "@variable.builtin", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "@variable.parameter", { fg = b.on_surface_variant })
  vim.api.nvim_set_hl(0, "@variable.member", { fg = b.on_surface })

  -- Constants and Strings - TERTIARY (color 1)
  vim.api.nvim_set_hl(0, "@constant", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "@constant.builtin", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "@string", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "@string.escape", { fg = b.tertiary })
  vim.api.nvim_set_hl(0, "@string.regex", { fg = b.tertiary })

  -- Functions - PRIMARY (color 2)
  vim.api.nvim_set_hl(0, "@function", { fg = b.primary })
  vim.api.nvim_set_hl(0, "@function.builtin", { fg = b.primary })
  vim.api.nvim_set_hl(0, "@function.method", { fg = b.primary })

  -- Keywords - SECONDARY (color 3)
  vim.api.nvim_set_hl(0, "@keyword", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "@keyword.function", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "@keyword.operator", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "@keyword.return", { fg = b.secondary })

  -- Types - PRIMARY (color 2)
  vim.api.nvim_set_hl(0, "@type", { fg = b.primary })
  vim.api.nvim_set_hl(0, "@type.builtin", { fg = b.primary })

  -- Properties - plain text
  vim.api.nvim_set_hl(0, "@property", { fg = b.on_surface })
  vim.api.nvim_set_hl(0, "@field", { fg = b.on_surface })

  -- Punctuation - muted
  vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = b.on_surface_variant })
  vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = b.on_surface_variant })

  -- Tags - SECONDARY (color 3)
  vim.api.nvim_set_hl(0, "@tag", { fg = b.secondary })
  vim.api.nvim_set_hl(0, "@tag.attribute", { fg = b.primary })
  vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = b.on_surface_variant })

  -- Telescope
  vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = c.outline, bg = c.surface_container })
  vim.api.nvim_set_hl(0, "TelescopePromptBorder", { fg = c.outline, bg = c.surface_container })
  vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { fg = c.outline, bg = c.surface_container })
  vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { fg = c.outline, bg = c.surface_container })
  vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = c.on_primary_container, bg = c.primary_container })
  vim.api.nvim_set_hl(0, "TelescopeMatching", { fg = b.primary, bold = true })
end

return M
