#!/usr/bin/env bash

log() {
    local program_name="$1" message="$2"

    notify-send -u low -h int:transient:1 "$program_name" "$message"
    echo "$program_name:: $message"
}

# log "$program_name" "$message"
