# Background / Foreground
background = #131315
foreground = #e5e1e3

# Selection
selection-background = #5d5d6c
selection-foreground = #e5e1e3

# Cursor
cursor-color = #e5e1e3
cursor-text = #131315

# Palette
palette = 0=#444559
palette = 1=#ffb4ab
palette = 2=#c4c5dd
palette = 3=#e0e0f9
palette = 4=#c6c5d6
palette = 5=#e5e1e3
palette = 6=#c4c5dd
palette = 7=#c6c5d6
palette = 8=#444559
palette = 9=#ffb4ab
palette = 10=#c4c5dd
palette = 11=#e0e0f9
palette = 12=#c6c5d6
palette = 13=#e5e1e3
palette = 14=#c4c5dd
palette = 15=#c6c5d6
