background #131315
foreground #e5e1e3
selection_foreground #e5e1e3
selection_background #5d5d6c
url_color #c6c5d6

# Black
color0 #444559
color8 #444559

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #c4c5dd
color10 #c4c5dd

# Yellow
color3 #e0e0f9
color11 #e0e0f9

# Blue
color4 #c6c5d6
color12 #c6c5d6

# Magenta
color5 #e5e1e3
color13 #e5e1e3

# Cyan
color6 #c4c5dd
color14 #c4c5dd

# White
color7 #c6c5d6
color15 #c6c5d6

# Cursor
cursor #e5e1e3
cursor_text_color #131315
